# composer for my streamlit app
version: '3.7'

services:
  streamlit:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    command:
      - streamlit
      - run
      - deploy/Accueil.py
